<?php

use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\NurseController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

// ─── PUBLIC ROUTE ─────────────────────────────────────────────────────────────
Route::get('/', function () {
    return view('welcome');
})->name('home');

// ─── SHARED PROTECTED ROUTES (all logged-in roles) ────────────────────────────
Route::middleware(['auth', 'verified'])->group(function () {

    // Dashboard — accessible to all roles after login
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    // Profile routes — generated by Breeze, do not remove
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // ── APPOINTMENTS (CRUD) ───────────────────────────────────────────────────
    // Admin and Patient access is controlled inside AppointmentController methods.
    // GET  /appointments             → AppointmentController@index
    // GET  /appointments/create      → AppointmentController@create
    // POST /appointments             → AppointmentController@store
    // GET  /appointments/{id}        → AppointmentController@show
    // GET  /appointments/{id}/edit   → AppointmentController@edit
    // PUT  /appointments/{id}        → AppointmentController@update
    // DELETE /appointments/{id}      → AppointmentController@destroy
    Route::resource('appointments', AppointmentController::class);
});

// ─── NURSE ROUTES ─────────────────────────────────────────────────────────────
// Protected by both 'auth' (must be logged in) and 'nurse' (must have nurse role).
Route::middleware(['auth', 'verified', 'nurse'])->group(function () {

    // GET  /nurse/appointments         → NurseController@index
    // Shows all appointments with patient name and current status.
    Route::get('/nurse/appointments', [NurseController::class, 'index'])
        ->name('nurse.appointments.index');

    // PATCH /nurse/appointments/{appointment}/status → NurseController@updateStatus
    // Nurse submits a status dropdown — only 'confirmed' or 'cancelled' allowed.
    Route::patch('/nurse/appointments/{appointment}/status', [NurseController::class, 'updateStatus'])
        ->name('nurse.appointments.updateStatus');
});

// ─── DOCTOR ROUTES ────────────────────────────────────────────────────────────
// Protected by both 'auth' (must be logged in) and 'doctor' (must have doctor role).
Route::middleware(['auth', 'verified', 'doctor'])->group(function () {

    // GET  /doctor/appointments        → DoctorController@index
    // Shows only appointments where doctor_name matches the logged-in doctor's name.
    Route::get('/doctor/appointments', [DoctorController::class, 'index'])
        ->name('doctor.appointments.index');

    // PATCH /doctor/appointments/{appointment}/note → DoctorController@addNote
    // Doctor submits a consultation note for a specific appointment.
    Route::patch('/doctor/appointments/{appointment}/note', [DoctorController::class, 'addNote'])
        ->name('doctor.appointments.addNote');
});

// ─── BREEZE AUTH ROUTES ───────────────────────────────────────────────────────
require __DIR__.'/auth.php';